[package]
name = "data_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
anyhow = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "macros", "postgres", "mysql", "sqlite", "mssql", "uuid", "json", "chrono", "bigdecimal"] }
mongodb = "2.6"
redis = { version = "0.24", features = ["tokio-comp"] }
cdrs = "7.0"
clickhouse-rs = { version = "0.3", features = ["tokio"] }
influxdb-client-rust = "1.1"
elasticsearch = "8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
bigdecimal = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "stream"] }